name: grape
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
  
    - family: DM_Serif_Text
      fonts:
        - asset: assets/fonts/DM_Serif_Text/DMSerifText-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter.ttf
        - asset: assets/fonts/Inter/Inter-italic.ttf
          style: italic
  assets:
    - assets/data/data.json