// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzPJeql_Ifv5GiZPtlk_aj4c6TQ0yi7Cw',
    appId: '1:1029952634629:web:ca1554a2a39ac7413d816c',
    messagingSenderId: '1029952634629',
    projectId: 'grape-8317a',
    authDomain: 'grape-8317a.firebaseapp.com',
    storageBucket: 'grape-8317a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ0gYhcxheuQY6l1OiwLpD9Tt4F5NhReI',
    appId: '1:1029952634629:android:f3e5638701866ab13d816c',
    messagingSenderId: '1029952634629',
    projectId: 'grape-8317a',
    storageBucket: 'grape-8317a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClSrg1c2ypjeC_6ayJxfyOJVf5s3miwq8',
    appId: '1:1029952634629:ios:93e09714e38e8e9d3d816c',
    messagingSenderId: '1029952634629',
    projectId: 'grape-8317a',
    storageBucket: 'grape-8317a.firebasestorage.app',
    iosBundleId: 'com.example.grape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClSrg1c2ypjeC_6ayJxfyOJVf5s3miwq8',
    appId: '1:1029952634629:ios:93e09714e38e8e9d3d816c',
    messagingSenderId: '1029952634629',
    projectId: 'grape-8317a',
    storageBucket: 'grape-8317a.firebasestorage.app',
    iosBundleId: 'com.example.grape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzPJeql_Ifv5GiZPtlk_aj4c6TQ0yi7Cw',
    appId: '1:1029952634629:web:03a7fb9b20f725573d816c',
    messagingSenderId: '1029952634629',
    projectId: 'grape-8317a',
    authDomain: 'grape-8317a.firebaseapp.com',
    storageBucket: 'grape-8317a.firebasestorage.app',
  );
}
